---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: What is InstructLab
    - name: module-01
      label: Getting Started with InstructLab
    - name: module-02
      label: Training and Serving a Model
    - name: module-03
      label: Conclusion
tabs:
  - name: "Double Terminals"
    port: 443
    secondary_port: 444
    path: /tty-top
    secondary_path: /tty-bottom
    user: instruct
    host: instructlab