:experimental: true
:imagesdir: ../assets/images

[#getting_started]
== Getting started with InstructLab

We created a CLI tool called ilab that implements a local LLM developer experience and workflow. The ilab CLI is written in Python and works on the following architectures:

. Apple M1/M2/M3 Mac
. Linux systems
. Windows 11 within a WSL environment

We anticipate support for more operating systems in the future. The system requirements to use the command line tool are as follows:

. C++ compiler
. Python 3.10, 3.11
. Approximately 60GB disk space (entire process)
.. Disk space requirements are dependent on several factors. Keep in mind that we will be generating data to feed to the model while also having the model locally on our system. For example, the model we are working with during this workshop is roughly 5gb in size.

// Use this section when leaving workshops up to reuse all day
// === Reset your machine

// Before proceeding, ensure your machine is ready for fun!

// **Run the following command to reset your system:**
// [source,console,role=execute,subs=attributes+]
// ----
// ~/files/reset/cleanup_and_reset.sh
// ----

---

[#installation]
=== Installing ilab

You will work with the Linux Terminal throughout this workshop. The terminal is an interface that allows users to communicate directly with the operating system by typing and executing commands.

The first thing we need to do is to source a Python virtual environment that will allow us to interact with the InstructLab command line tools. While you have two terminal windows available on your right, let's start with the *upper* window.

WARNING: Several steps in this section involving installation and configuration of InstructLab were already completed for speed and security. The title "Reference" will appear above code blocks that have already been completed and will ERROR if executed. These steps are included for reference only.

IMPORTANT: Code blocks with the *Command* titles should be exectued as normal.

. Navigate to the preset InstructLab directory and activate the Python virtual environment by running the following commands:

.Command
[source,console,role=execute,subs=attributes+]
----
cd ~/instructlab
----

.Command
[source,console,role=execute,subs=attributes+]
----
source venv/bin/activate
----

.Your prompt should now look like this

.Output
[source,console]
----
(venv) [instruct@instructlab instructlab]$
----


[start=2]
. Reference for using pip to install command the instructlab command line utility *ilab*:

.Reference
[source,console,subs=attributes+]
----
pip3 install git+https://github.com/instructlab/instructlab.git@v0.19.3
----

[start=3]
. To verify the *ilab* utility has been installed, user the ilab command inside your virutal environment:

.Command
[source,console,role=execute,subs=attributes+]
----
ilab
----


To verify the version run the below command:

.Command
[source,console,role=execute,subs=attributes+]
----
ilab --version
----


If everything has been installed correctly, you should see the following output:

.Output
[source,console]
----
Usage: ilab [OPTIONS] COMMAND [ARGS]...


  CLI for interacting with InstructLab.


  If this is your first time running ilab, it's best to start with `ilab config init`
  to create the environment.


Options:
  --config PATH  Path to a configuration file.  [default: /home/instruct/.config/instructlab/config.yaml]
  -v, --verbose  Enable debug logging (repeat for even more verbosity)
  --version      Show the version and exit.
  --help         Show this message and exit.

Commands:
  config    Command Group for Interacting with...
  data      Command Group for Interacting with...
  model     Command Group for Interacting with...
  system    Command group for all system-related...
  taxonomy  Command Group for Interacting with...

Aliases:
  chat      model chat
  generate  data generate
  serve     model serve
  train     model train
----


*Congratulations!* You now have verified the installation and are ready to dive into the world of LLM alignment!

[#configuration]
=== Configuring ilab

Now verified the installation and command-line tool, the next step is to initialize the local environment so that we can begin working with the model. This step was completed for you with the below *init* command.


Step 1: Reference for initializing ilab:

.Reference
[source,console,role=execute,subs=attributes+]
----
ilab config init
----

NOTE: The output of this command will allow you to configure various settings and file locations. The below references these options. It is also possible to skip these by including a *--non-interactive* argument after the init command. All default values selected for the configuration of this lab.

.Reference
[source,console]
----
Welcome to InstructLab CLI. This guide will help you to setup your environment.
Please provide the following values to initiate the environment [press Enter for defaults]:
Path to taxonomy repo [/home/instruct/.local/share/instructlab/taxonomy]:
----

NOTE: Press kbd:[ENTER] for all default settings.

.Reference
[source,console]
----
Path to your model [/home/instruct/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf]:
Generating `/home/instruct/.config/instructlab/config.yaml`...
Detecting Hardware...
We chose Nvidia 1x L4 as your designated training profile. This is for systems with 24 GB of vRAM.
This profile is the best approximation for your system based off of the amount of vRAM. We modified it to match the number of GPUs you have.
Is this profile correct? [Y/n]: Y
----

NOTE: **For this lab**, we are using a single NVIDIA A10 GPU and this training profile is appropriate. Other environments may need different profiles.

.Reference
[source,console]
----
Initialization completed successfully, you're ready to start using `ilab`. Enjoy!
----

** Several things happen during the initialization phase: A default taxonomy is created on the local file system, and a configuration file (config.yaml) is created in the 'home/instruct/.config/instructlab/' directory.
* The config.yaml file contains defaults we will use during this workshop. After this workshop, when you begin playing around with InstructLab, it is important to understand the contents of the configuration file so that you can tune the parameters to your liking.

[#download]
=== Download the models

With the InstructLab environment configured, the next step is to download quantized (compressed and optimized) models to your local directory. These steps have already been executed for you and are here as a reference. Granite will be used as a model server for API requests, and Merlinite will help create synthetic data to train a new model.

*Step 1*: The `ilab model download` command is used to pull models from our source.

Reference for Granite and Merlinite download commands:

.Reference
[source,console,subs=attributes+]
----
ilab model download --repository instructlab/granite-7b-lab-GGUF --filename=granite-7b-lab-Q4_K_M.gguf
----

.Reference
[source,console,subs=attributes+]
----
ilab model download --repository instructlab/merlinite-7b-lab-GGUF --filename=merlinite-7b-lab-Q4_K_M.gguf
----

The `ilab model download` command downloads a model from the HuggingFace InstructLab organization that we used for this workshop.

The output after each download command resembles the following:

.Reference
[source,console]
----
Downloading model from Hugging Face: instructlab/granite-7b-lab-GGUF@main to /home/instruct/.cache/instructlab/models...
Downloading 'granite-7b-lab-Q4_K_M.gguf' to '/home/instruct/.cache/instructlab/models/.cache/huggingface/download/granite-7b-lab-Q4_K_M.gguf.6adeaad8c048b35ea54562c55e454cc32c63118a32c7b8152cf706b290611487.incomplete'
INFO 2024-09-10 16:51:32,740 huggingface_hub.file_download:1908: Downloading 'granite-7b-lab-Q4_K_M.gguf' to '/home/instruct/.cache/instructlab/models/.cache/huggingface/download/granite-7b-lab-Q4_K_M.gguf.6adeaad8c048b35ea54562c55e454cc32c63118a32c7b8152cf706b290611487.incomplete'
granite-7b-lab-Q4_K_M.gguf: 100%|█| 4.08G/4.08G [00:19<00:00, 207
Download complete. Moving file to /home/instruct/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf
INFO 2024-09-10 16:51:52,562 huggingface_hub.file_download:1924: Download complete. Moving file to /home/instruct/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf
----

With the models downloaded, we can serve and chat with the Granite model. Serving the model simply means we are going to run a server that will allow other programs to interact with the data similar to making an API call.

IMPORTANT: The code blocks marked *Reference* are complete, proceed executing each *Command* as prompted from this point on.

[#serve]
=== Serving the model

Let's serve the model by running the following command in the same terminal window:

.Command
[source,console,role=execute,subs=attributes+]
----
ilab model serve --model-path /home/instruct/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf
----

As you can see, the serve command can take an optional `-–model-path` argument. In this case, we want to serve the Granite model. If no model path is provided, the default value from the `config.yaml` file will be used.

Once the model is served and ready, you will see the following output:

.Output
[source,console,subs=quotes]
----
INFO 2024-09-10 18:12:09,459 instructlab.model.serve:145: Using model '/home/instruct/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
INFO 2024-09-10 18:12:09,459 instructlab.model.serve:149: Serving model '/home/instruct/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf' with llama-cpp
INFO 2024-09-10 18:12:16,023 instructlab.model.backends.llama_cpp:250: Replacing chat template:
 {% for message in messages %}
{% if message['role'] == 'user' %}
{{ '<|user|>
' + message['content'] }}
{% elif message['role'] == 'system' %}
{{ '<|system|>
' + message['content'] }}
{% elif message['role'] == 'assistant' %}
{{ '<|assistant|>
' + message['content'] + eos_token }}
{% endif %}
{% if loop.last and add_generation_prompt %}
{{ '<|assistant|>' }}
{% endif %}
{% endfor %}
INFO 2024-09-10 18:12:16,026 instructlab.model.backends.llama_cpp:193: Starting server process, press CTRL+C to shutdown server...
INFO 2024-09-10 18:12:16,026 instructlab.model.backends.llama_cpp:194: After application startup complete see http://127.0.0.1:8000/docs for API.
----

*WOOHOO!* You just served the model for the first time and are ready to test out your work so far by interacting with the LLM. We are going to accomplish this by chatting with the model.

[#chat]
=== Chat with the model

Because you’re serving the model in one terminal window, you will have to use a separate terminal window and re-activate your Python virtual environment to run the `ilab chat` command and communicate with the model you are serving.

. In the *bottom* terminal window, issue the following commands:

.Command
[source,console,role=execute,subs=attributes+]
----
cd ~/instructlab
source venv/bin/activate
----

.Output
.Your prompt should now look like this
[source,console]
----
(venv) [instruct@instructlab instructlab]$
----

[start=2]
. Now that the environment is sourced, you can begin a chat session with the `ilab chat` command:

.Command
[source,console,role=execute,subs=attributes+]
----
ilab model chat -m /home/instruct/.cache/instructlab/models/granite-7b-lab-Q4_K_M.gguf
----


You should see a chat prompt like the example below.

.Output
[source,console]
----
╭───────────────────────────────────────────────────────────────────────────╮
│ Welcome to InstructLab Chat w/ GRANITE-7B-LAB-Q4_K_M.GGUF (type /h for help)                                                                                                                                      
╰───────────────────────────────────────────────────────────────────────────╯
>>> 
----

[start=3]
. At this point, you can interact with the model by asking it a question. Example:

.Command
[source,console,role=execute,subs=attributes+]
----
What is OpenShift in 20 words or less?
----

Wait, wut? That was AWESOME!!!!! You now have your own local LLM running on this machine. That was pretty easy, huh?

=== Next Steps

You've now successfully installed the ilab CLI, initialized the local environment, downloaded the model, served the model, and chatted with the model. You're now ready to move on to the next module, where you will learn how to train and serve a new model.