:experimental: true

[#getting_started]
== Getting started

Install ilab command line interface
We created a CLI tool called ilab that implements a local LLM developer experience and workflow. The ilab CLI is written in Python and works on the following architectures:

. Apple M1/M2/M3 Mac
. Linux systems

We anticipate support for more operating systems in the future. The system requirements to use the command line tool are as follows:

. C++ compiler
. Python 3.9+
. Approximately 60GB disk space (entire process)
.. Disk space requirements are dependent on several factors. Keep in mind that we will be generating data to feed to the model while also having the model locally on our system. For example, the model we are working with during this workshop is roughly 5gb in size.

[#installation]
=== Installing ilab

The first thing we need to do is to source a Python virtual environment that will allow us to interact with the InstructLab command line tools.

. Activate the python venv environment by running the following commands:
+

[source,sh,role=execute,subs=attributes+]
----
cd ~/instructlab
source venv/bin/activate
----
+
.Your Prompt should now look like this

[source,sh]
----
(venv) [instruct@instructlab instructlab]$ 
----
+

. Install the command line tool using the pip command
+

[source,sh,role=execute,subs=attributes+]
----
pip3 install git+https://github.com/instructlab/instructlab.git@v0.17.1

----
+

NOTE: `pip install` may take some time, depending on the internet connection available at the conference or if the files have been cached locally.

. From your venv environment, verify ilab is installed correctly by running the ilab command.
+

[source,sh,role=execute,subs=attributes+]
----
ilab
----
+

Assuming that everything has been installed correctly, you should see the following output:
+

[source,sh,role=execute,subs=attributes+]
----
Usage: ilab [OPTIONS] COMMAND [ARGS]...


  CLI for interacting with InstructLab.


  If this is your first time running ilab, it's best to start with `ilab init`
  to create the environment.


Options:
  --config PATH  Path to a configuration file.  [default: config.yaml]
  --version      Show the version and exit.
  --help         Show this message and exit.


Commands:
  chat      Run a chat using the modified model
  check     (Deprecated) Check that taxonomy is valid
  convert   Converts model to GGUF
  diff      Lists taxonomy files that have changed since <taxonomy-base>...
  download  Download the model(s) to train
  generate  Generates synthetic data to enhance your example data
  init      Initializes environment for InstructLab
  list      (Deprecated) Lists taxonomy files that have changed since <taxonomy-base>.
  serve     Start a local server
  test      Runs basic test to ensure model correctness
  train     Takes synthetic data generated locally with `ilab generate`...
----


*Congratulations!* You now have everything installed and are ready to dive into the world of LLM alignment!

[#initialize]
== Initialize ilab

Now that we know that the command-line interface `ilab` is working correctly, the next thing we need to do is initialize the local environment so that we can begin working with the model. This is accomplished by issuing a simple init command.


Step 1: Initialize ilab by running the following command:

[source,sh,role=execute,subs=attributes+]
----
ilab config init
----
.You should see the following output:
[source,sh]
----
Found config.yaml in the current directory, do you still want to continue? [y/N]: y
Welcome to InstructLab CLI. This guide will help you to setup your environment.
Please provide the following values to initiate the environment [press Enter for defaults]:
----

NOTE: When prompted to accept the `config.yaml`, hit kbd:[ENTER] 

[source,sh]
----
Path to taxonomy repo [taxonomy]:
----

NOTE: When prompted to provide the path to the taxonomy repo, hit kbd:[ENTER] 

[source,sh]
----
`taxonomy` seems to not exist or is empty. Should I clone git@github.com:instruct-lab/taxonomy.git for you? [y/N]: y
----

NOTE: If asked if the CLI should clone the taxonomy repo, input 'y' as shown in the above output.

[source,sh]
----
Cloning git@github.com:instruct-lab/taxonomy.git...
Generating `config.yaml` in the current directory...
Initialization completed successfully, you're ready to start using `ilab`. Enjoy!
----

NOTE: When asked to enter a directory for the model file, use the default and hit <ENTER>

[source,sh]
----
Path to your model [models/merlinite-7b-lab-Q4_K_M.gguf]:
----

* Several things happen during the initialization phase: A default taxonomy is created on the local file system, and a configuration file (config.yaml) is created in the current directory.
* The config.yaml file contains defaults we will use during this workshop. After this workshop, when you begin playing around with InstructLab, it is important to understand the contents of the configuration file so that you can tune the parameters to your liking

[#download]
=== Download the models

*Step 1*: Run the `ilab download` command.

[source,sh,role=execute,subs=attributes+]
----
ilab model download --repository instructlab/granite-7b-lab-GGUF --filename=granite-7b-lab-Q4_K_M.gguf
----

[source,sh,role=execute,subs=attributes+]
----
ilab model download --repository instructlab/merlinite-7b-lab-GGUF --filename=merlinite-7b-lab-Q4_K_M.gguf
----

The ilab download command downloads a model from the HuggingFace instructlab organization that we will use for this workshop. 

The output should look like the following:

NOTE: *This command may not show the contents if the model is being cached on the local machine.*

[source,sh]
----
Downloading model from downloading model from instructlab/granite-7b-lab-GGUF@main to models...                                                                                                                                                 
Downloading 'granite-7b-lab-Q4_K_M.gguf' to 'models/.huggingface/download/granite-7b-lab-Q4_K_M.gguf.6adeaad8c048b35ea54562c55e454cc32c63118a32c7b8152cf706b290611487.incomplete'
INFO 2024-05-06 16:46:24,394 file_download.py:1877 Downloading 'granite-7b-lab-Q4_K_M.gguf' to 'models/.huggingface/download/granite-7b-lab-Q4_K_M.gguf.6adeaad8c048b35ea54562c55e454cc32c63118a32c7b8152cf706b290611487.incomplete'100%|█████████████████████████████████████████████████████████████| 4.08G/4.08G [00:36<00:00, 110MB/s]

----


Now that the models have been downloaded, we can serve and chat with the model. Serving the model simply means we are going to run a server that will allow other programs to interact with the data similar to making an API call. 

[#serve]
=== Serving the model

Serve the model by running the following command:

[source,sh,role=execute,subs=attributes+]
----
ilab model serve --model-path models/granite-7b-lab-Q4_K_M.gguf
----

As you can see, the serve command can take an optional `-–model-path` argument. In this case, we want to serve the Granite model. If no model path is provided, the default value from the config.yaml file will be used. 
Once the model is served and ready, you’ll see the following output:

[source,sh]
----
INFO 2024-04-23 17:16:53,903 lab.py:296 Using model '/models/granite-7b-lab-Q4_K_M.gguf' with -1 gpu-layers and 4096 max context size.
INFO 2024-04-23 17:17:02,861 server.py:155 Starting server process, press CTRL+C to shutdown server...
INFO 2024-04-23 17:17:02,861 server.py:156 After application startup complete see http://127.0.0.1:8000/docs for API.
----

*WOOHOO!* You just served the model for the first time and are ready to test out your work so far by interacting with the LLM. We are going to accomplish this by chatting with the model.

[#chat]
=== Chat with the model

Because you’re serving the model in one terminal window, you will have to create a new window and re-activate your Python virtual environment to run the ilab chat command. 
Note: You can open a new tab in your terminal by hitting the command-t keyboard combination. If you need assistance, please ask a Red Hatter in the InstructLab Lounge.

In the other terminal window, Issue the following commands:

[source,sh,role=execute,subs=attributes+]
----
cd ~/instructlab
source venv/bin/activate
----
.Your Prompt should now look like this
[source,sh]
----
(venv) [instruct@instructlab instructlab]$ 
----

Now that the environment is sourced, you can begin a chat session with the ilab chat command:


[source,sh,role=execute,subs=attributes+]
----
ilab model chat -m models/granite-7b-lab-Q4_K_M.gguf
----


You should see a chat prompt

[source,sh]
----
╭───────────────────────────────────────────────────────────────────────────╮
│ Welcome to Chat CLI w/ MODELS/GRANITE-7B-LAB-Q4_K_M.GGUF (type /h for help)                                                                                                                                        
╰───────────────────────────────────────────────────────────────────────────╯
>>> 
----


At this point, you can interact with the model by asking it a question. Example:
What is openshift in 20 words or less?

[source,sh,role=execute,subs=attributes+]
----
What is openshift in 20 words or less?
----

Wait, wut? That was AWESOME!!!!! You now have your own local LLM running on this laptop. That was pretty easy, huh?

=== Next Steps

You've now successfully installed the ilab CLI, initialized the local environment, downloaded the model, served the model, and chatted with the model. You're now ready to move on to the next module, where you will learn how to train and serve a new model.